- README.rst
There are a TON of badges listed on [shields.io](http://shields.io/) Having a bunch on the repo I think will make it look cluttered. Badges are a great way for someone to get a quick look at the code vitals. I think including the current version available in the package manager is a good thing for someone to get at a glace.
Also I promise this will be my last PR for these badges.
> Last pull request for badges

- arcade/window_commands.py
First pull request for adding type hints.
> Add type hints to window_commands.py

- arcade/sound.py
- setup.py
* Reorganize the two copies of `avbin.dll` for Windows, and put them in the same directory
* Reorganize `setup.py` to identify only the version of the included avbin library that needs installed
* Make `setup.py` use a context manager to read the readme file
* Reorganize `arcade/sound.py` to load the specific avbin library that was installed
> Reorganize avbin

- doc/installation_mac.rst
I can't really test the early parts of these instructions, as I'm not going to wipe my Mac back to a clean slate, but they should work fine.  I'm more familiar with markdown than RST, so please look at formatting and markup.  Also, any feedback on instruction wording would be greatly appreciated.
> Update installation instructions for Mac

- arcade/draw_commands.py
Add some more coverage for the parts I could understand. Not sure yet about making VertexBuffers in doctests.
> Add some more coverage for the parts I could understand. Not sure yet about making VertexBuffers in doctests.

- arcade/sprite.py
Walk up animation texture was named `walk_up_walk_texture`, instead of `walk_up_texture`
> Walk up walk fix

- arcade/sprite.py
Fix #72 (AnimatedTimeSprite did not scale either)
> Fix animated sprite scaling

- examples/snow.py
As requested at the link below, I created a small snow simulation for the example code set:
https://pythonhosted.org/arcade/examples/examples_to_do.html
I read the instructions on how to contribute carefully and didn't think I had to recompile the library for this, but please tell me if I'm missing something.
Let me know if there's anything I can do to improve the code or make it more educational.
Happy Holidays!
> Added snow example

- arcade/sprite.py
https://github.com/pvcraven/arcade/issues/169
Apart from this, I don't really see what else I can change without breaking things
> SpriteList.move() code needs to be cleaned up

- arcade/application.py
Please review, as I am not sure if what I removed, in addition to changing `set` to `get`, is useful or not in the context of this `get` method.
> Fix docstring. Please review the diff.

- arcade/examples/sprite_moving_platforms.py
- arcade/examples/sprite_ramps.py
- arcade/examples/sprite_tiled_map.py
Distance calculations for side-scroller examples based on actual pixels being rendered. Game Over decision based on size of tiled map.
> Issue #190: Update distance calculations in scrolling examples

- doc/distribute_macos.rst
- doc/examples/briefcase__main__.py
- doc/examples/briefcase_app.py
- doc/examples/install_requires.py
- doc/index.rst
Adds MacOS-specific documentation for bundling/distribution.
TODOs:
> [WIP] Begins adding MacOS distribution documentation

- doc/how_to_compile.rst
> Howto compile linux corrections

- arcade/sprite.py
> removed second definition of set_position()

- arcade/draw_commands.py
> Fix naming of x and y coordinates in *_xywh_* functions

- CONTRIBUTING.md
- doc/how_to_compile.rst
- doc/how_to_submit_changes.rst
- added missing dependencies to documentation
- updated "make" syntax in documentation
(My first PR on GitHub. Open to any suggestions.)
> Correct the build instructions in "How to Compile" docs (#293)

- arcade/examples/tetris.py
> Fix tetris exception on startup (#305)

- arcade/examples/sprite_properties.py
- doc/examples/examples_to_do.rst
I didn't know if when the [Example to-do list](http://arcade.academy/examples/examples_to_do.html) mentioned "sprites with a property", it meant:
* A simple Python data attribute dynamically added to each `Sprite` instance?
* A class derived from `Sprite` that added a data attribute?
* Use of Python's `@property` decorator?
It seems the examples are directed at beginning coders, so I went with the first option which felt the most accessible to a new coder.  I can easily change it if desired.
> Add example that demonstrates how to use properties on sprites (#302)

- arcade/examples/dual_stick_shooter.py
Also added some joystick debug logging. These debug functions are not intended to be permanent.
> Fix ship rotation and add game over message in dual-stick shooter example #301

- arcade/examples/perlin_noise_1.py
- arcade/examples/perlin_noise_2.py
This doesn't fully "fix" these examples, but gets rid of obvious exceptions.  I'm not sure what the expected behavior is when the user clicks a cell.
> Incremental improvements in perlin noise examples #310 #305

- arcade/examples/sound.py
- arcade/examples/sprite_csv_map.py
- arcade/examples/sprite_enemies_in_platformer.py
- arcade/examples/sprite_face_left_or_right.py
- arcade/examples/sprite_move_angle.py
- arcade/examples/sprite_move_joystick.py
- arcade/examples/sprite_move_keyboard.py
- arcade/examples/sprite_move_keyboard_better.py
- arcade/examples/sprite_move_scrolling.py
- arcade/examples/sprite_move_walls.py
- arcade/examples/sprite_moving_platforms.py
- arcade/examples/sprite_no_coins_on_walls.py
- arcade/examples/sprite_ramps.py
- arcade/examples/sprite_rooms.py
- arcade/examples/sprite_simple_platformer.py
- arcade/examples/stress_test_collision.py
> Remove unnecessary score variable from examples & fix sound.py to work with "python -m ..." (#314)

- arcade/examples/pymunk_2.py
- arcade/examples/sprite_change_coins.py
- arcade/examples/sprite_tiled_map_with_levels.py
- pymunk_2.py: fixed startup crash by using newer text API
- sprite_change_coins.py: fixed touched sprites not changing
- sprite_tiled_map_with_levels.py: If player is in the middle of a jump while triggering transition from level 1 to level 2, character can fall out of the level. Fix that.
> Fix some broken example apps (#326)

- arcade/examples/particle_stress.py
A single Emitter with a lot of particles, a lot of emitting, and a lot of reaping.  Useful for profiling to see the hotspots: SpriteList.calculate_sprite_buffer() and SpriteList.remove().
> Add particle stress test example #333

- arcade/application.py
Fixes issue #340 on my Nvidia GTX 850 machine running Ubuntu 18.04.
> Fix issue #340 on some machines

- arcade/read_tiled_map.py
- tests/unit2/test_isometric.py
- tests/unit2/test_sound.py
Everything should be fairly self explanatory, but I will go through it all just to be sure.
I added the ability to specify the tsx file used with the tmx. If the file is not specified, I also made the import auto-magically attempt to find the correct directory to look for the tsx file in. This all seems to work, but I am honestly probably too new to the arcade library to say that for sure.
I also made some of the tests use pathlib, because I could not run them on my Debian machine without doing that.
Feedback is greatly appreciated, because I am very new to this!
Oh, big thing, I had to disable the sound_test because I could not get it to work. I'm not sure what the procedure for that is but disabling it on the whole repo is probably not the right call.
> Fix for #360 as well as updating the test code to be cross platform

- tests/unit2/test_buffered_drawing.py
Test added to test Issue #379 . Looks like things are working as expected.
> Add/Modify working test for buffered_drawing.

- arcade/sprite.py
This solves Issue #376 . Testing with my example code i have yet to merge.
> Use tuple unpacking to solve issue #376

- doc/examples/platform_tutorial/index.rst
- doc/index.rst
- doc/sample_games.rst
Also made quick doc fix to Kayzee Game example
> Add links to PyCon 2019 tutorial YouTube vid

- arcade/examples/perf_test/stress_test_draw_moving_pygame.py
flake8 testing of https://github.com/pvcraven/arcade on Python 3.7.1
$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./doc/examples/install_requires.py:3:20: E999 SyntaxError: invalid syntax
install_requires=[
^
./arcade/examples/text_loc_example_done.py:58:13: F821 undefined name '_'
_("Simple line of text in 12 point"), start_x, start_y, arcade.color.BLACK, 12
^
./arcade/examples/perf_test/stress_test_draw_moving_pygame.py:262:5: F821 undefined name 'plt'
plt.plot(window.sprite_count_list, window.processing_time_list, label="Processing Time")
^
./arcade/examples/perf_test/stress_test_draw_moving_pygame.py:263:5: F821 undefined name 'plt'
plt.plot(window.sprite_count_list, window.drawing_time_list, label="Drawing Time")
^ …
```
> Undefined name: import matplotlib.pyplot as plt

- arcade/examples/different_screens_example.py
- arcade/examples/different_screens_minimal.py
- arcade/examples/different_screens_pause.py
Update docs in the other View examples to reflect the current View implementation.
> Add a very minimal example of how to use the View class. #448

- arcade/application.py
- tests/unit2/test_window.py
Also added checks to the window test to make sure the arguments get passed to the window correctly.
Fixes #494.
> Fix resizable passed as fullscreen

- arcade/text.py
I've changed the ValueError messages of anchor_x and anchor_y to match the conditionals.
> Corrected anchor ValueError messages

- arcade/tilemap.py
- tests/unit2/test_tilemap.py
Modify the problem that the image display position and TMX cannot correspond
> Fix image position

- arcade/application.py
- arcade/arcade_types.py
- arcade/buffered_draw_commands.py
- arcade/draw_commands.py
- arcade/emitter.py
- arcade/emitter_simple.py
- arcade/examples/asteroid_smasher.py
- arcade/examples/bouncing_ball.py
- arcade/examples/bouncing_rectangle.py
- arcade/examples/platform_tutorial/11_animate_character.py
- arcade/examples/radar_sweep.py
- arcade/examples/sprite_explosion.py
- arcade/examples/sprite_move_animation.py
- arcade/geometry.py
- arcade/particle.py
- arcade/read_tiled_map.py
- arcade/shader.py
- arcade/sound.py
- arcade/sprite.py
- arcade/sprite_list.py
- arcade/text.py
- arcade/tilemap.py
- arcade/window_commands.py
- make.bat
- mypy.ini
- requirements_dev.txt
- tests/unit2/test_sprite_collision.py
Also some Code Inspection errors reported by PyCharm
> Clean up type checking errors reported by mypy #482

- .gitignore
- arcade/gui.py
Added possibility to create custom TextButtons with different font colors faster.
Behavior added:
If the user passes theme argument font_color is taken from the theme
If not and user passes font_color argument the color is set to what they passed.
If the don't pass neither the color is set to face_color.
> Added fonc_color arg to gui.TextButton init

- arcade/tilemap.py
Fix for issue #535, also contains fixes for #527 and #529
> Issue tiles in object layers not placed properly

- arcade/tilemap.py
Contains the proposed fix for #529 and #527 - sorry for the confusion.
> Issue object layers not processing properties

- requirements.txt
Force new version of pyglet to solve #514
> Update requirements for pyglet >=1.4.8

- arcade/sprite_list.py
- tests/unit2/test_sprite_list.py
Let me know if something is not as you like it, or if you have doubts about certain parts.
Kind regards,
Maarten
> Added extend, insert and remove methods to spritelist.

- arcade/text.py
> Make draw_text return text_sprite

- arcade/text.py
There was repeated code with an error when the text_sprite was created for the first time. It would not calculate the `center_y` property correctly. I refactored the function to eliminate the duplication and fix the problem.
Resolves #566
> Fix issue with text_sprite anchor_y == "top"

- arcade/sprite.py
> Update sprite.py for absolute rotate_point

- make.sh
I had commented these out to shorten the setup process and forgot to uncomment them before pushing.
> re-add tests and documentation after install

- arcade/gui.py
- tests/unit2/test_gui_theme.py
I have wrote tests for gui.Theme and changed the class some. I can continue this work if you approve.
> Tests for gui.Theme

- arcade/tilemap.py
This is a great feature and easy to integrate.  Please pull ASAP! :)
> Implement Size and Rotation for Tiled Objects

- arcade/tilemap.py
Another nice to have easy to implement feature :)
> Implement opacity for TMX object and tile layers

- arcade/tilemap.py
Add type and name to sprite properties from TMX object
Add type to sprite properties from TMX tile
> Tmx properties

- arcade/experimental/camera.py
Added a 2D Camera class for translating position, zooming in/out, and scaling when resizing
> Added 2D Camera class

- arcade/experimental/camera.py
Cleaned up some code and added margin variables for each side (`left` `right` `bottom` `top`), and a function to set them.
> Added the ability to set margins on camera

- arcade/application.py
To allow other components to push handlers for `on_update` and `update` they are now dispatched as event.
> Dispatch update and on_update as pyglet event

- arcade/drawing_support.py
- arcade/geometry.py
- tests/unit2/test_calculate_points.py
- tests/unit2/test_is_point_in_poligons.py
Creating an empty label caused an IndexError in collides_with_point , this is fixed with the given changes
> fix is_point_in_poligons and calculate_points for empty images

- arcade/gl/texture.py
- tests/unit2/test_opengl_texture.py
> Fix wrong exception type on bad type passed to texture write

- arcade/gui/core.py
- arcade/gui/elements/__init__.py
- arcade/gui/elements/inputbox.py
- arcade/gui/examples/show_id_example.py
- arcade/gui/manager.py
- arcade/gui/ui_style.py
- arcade/gui/utils.py
- tests/test_gui/test_ui_clickable_interactions.py
- tests/test_gui/test_ui_inputbox.py
- tests/test_gui/test_ui_manager_callbacks.py
I replaced the direct property access in UIEvent with a `get` method.
Will have some thoughts about replacing the UIEvent with type with a UIEvent subclassing approach. That would make mypy more effective.
> Fix mypy issues in new GUI code

- arcade/gui/core.py
- arcade/gui/elements/image_button.py
- arcade/gui/elements/inputbox.py
- arcade/gui/elements/label.py
- arcade/gui/ui_style.py
- tests/test_gui/test_ui_element.py
- tests/test_gui/test_ui_label.py
- tests/test_gui/test_ui_style.py
This will fix the issue most of the UIElements, Image_Button and InputBox still have some issues.
Will this address next.
> Fix 711 - style changes not applied after UIElement added to UIManager

- arcade/application.py
- arcade/examples/gui_custom_style.py
- arcade/examples/gui_elements.py
- arcade/gui/examples/show_all.py
- arcade/gui/examples/show_decorator_example.py
- arcade/gui/examples/show_id_example.py
- arcade/gui/examples/show_image_from_style.py
- arcade/gui/examples/show_uiflatbutton.py
- arcade/gui/examples/show_uiflatbutton_custom_style.py
- arcade/gui/examples/show_uiinputbox.py
- arcade/gui/examples/show_uilabel.py
- tests/unit/test_view.py
From my point of view this looks better then #714
> New callbacks for setup and teardown of a view

- arcade/sound.py
Adds `is_complete()` method to `arcade.Sound`. For issue #727.
> Allow checking if a sound has completed playing.

- arcade/tilemap.py
> Take margin and spacing into account when calculating sprite sheet coordinates.
