arcade/sprite.py

The AnimatedWalkingSprite can now display Upwards and Downwards facing sprites.
When holding a direction and pressing a second button that is orthogonal to the first, the change in direction will be ignored.
Addresses Issue #68

Fix AnimatedWalkingSprite

---

arcade/physics_engines.py

Simply remove another variable when completing the task, then returning the value necessary.
Seems a better alternative to creating a variable with a default value, performing a check, modifying said variable if necessary, and returning.

Tiny modification when returning

---

arcade/examples/pymunk_platformer/create_level.py
arcade/examples/pymunk_platformer/main_window.py
arcade/examples/pymunk_platformer/physics_utility.py

Sorry for the nitpicking, but from experience I know that asterisk imports are confusing to newbies.

Change to explicit imports

---

.travis.yml
doc/conf.py
doc/generate_example_thumbnails.py
make.bat
make.sh

Issue #206 
When sphinx-build runs it opens and executes the file `doc/conf.py`. 
I made `doc/conf.py` call `doc/preprocess_files.py`.
I removed `preprocess_files.py` calls from `make.bat`, `make.sh` and `travis.yaml` 
I created `doc/generate_example_thumbnails.py`.
It checks for the directory `doc/examples/thumbs`. If that directory exists the script does nothing. If the directory does not exist it executes the appropriate command to generate the thumbnails.
`doc/conf.py` makes the call to `doc/generate_example_thumbnails.py`.
This PR does have some issues.
- I commented out the line in `generate_example_thumbnails.py` that creates the gifs. The generated documentation and the live documentation are currently not using gif thumbnails.
- I can not test this on windows or macOS. I do not …

Automate thumbnail generation

---

arcade/examples/starting_template.py

It references sprite_starting_template as the filename rather than just starting_template.

Fix typo in file docstring

---

arcade/sound.py

With this change, sound.py will not crash when executed in virtualenv. virtualenv is used by PyInstaller.
See issue #215.

Handle missing site.getsitepackages attribute in sound.py for virtualenv compatibility.

---

arcade/application.py

This enables access to the window instance through arcade.get_window(), if one is using a custom window class. As a new user I expected arcade.get_window() to give me current window instance. I was quite disappointed when this was not the case. I was able to achieve it by using this code:
`
window = MyWindow()
window.setup()
arcade.set_window(window)
arcade.run()
`
It works, but it would be nice if it was done automatically on window creation.

Setting window as arcades window

---

arcade/sound.py

#199 
This might need some work before being merged.
This tries to load avbin from the user directory, if pyglet raises an ImportError then it tries to load avbin from the global site directory.
- It does not handle the ImportError appropriately if avbin can not be loaded at all.
- It does not log any information.
- I am unsure why hasattr() is being called for getsitepackages() and if I should be doing it for getuserbase().

Attempts to load avbin from user site before global site

---

arcade/sound.py

This commit fixes sound playback on Linux (issue #224). As suggested by @dangillet, WAV files are loaded to memory as StaticSource and are played back by multiple players.
This fix assumes that WAV files are used for short sound effects only. A better solution would be to distinguish between sound and music in the API as suggested by @dangillet.

Fix sound playback of WAV files on Linux.

---

arcade/sprite.py

After sprite.kill() the sprite was still tracking the SpriteLists it was member of.

Clean self.spritelists after Sprite.kill().

---

arcade/examples/full_screen_example.py

As discussed in #260, this PR just makes a minor improvement to the example code, showing a better way to toggle full screen mode.
I grepped the `examples` directory (looking for `self.is_full_screen = not self.is_full_screen`) and only `full_screen_example.py` needed editing.
Thanks

Improved the example code showing how to toggle full screen mode.

---

arcade/sound.py

using fix proposed by MushroomMaula (https://github.com/pvcraven/arcade/issues/249)
Tested with make test both inside and outside virtualenv, also tested with [Blake Dalmas' "The Great Skeleton War"](https://github.com/BlakeDalmas/Python/tree/master/The%20Great%20Skeleton%20War)

Fix for issue #249 (avbin not working when using inside virtualenv)

---

doc/release_notes.rst

Minor syntax fix. The features under release notes v1.3.2 is rendered as a single row. I added the `*` prefix.

Changed features in v1.3.2 from single row to list

---

arcade/draw_commands.py

When loading textures they are [cached for speed up](https://github.com/pvcraven/arcade/blob/master/arcade/draw_commands.py#L268). But when working with images that contain a texture set the [image file is reloaded by PIL for each texture of the set](https://github.com/pvcraven/arcade/blob/master/arcade/draw_commands.py#L294). This makes loading tile maps with tile sets unnecessary slow. This PR also adds the texture set image file to the cache improving loading speed by orders of magnitude.

Cache image files with texture sets for speed up

---

arcade/buffered_draw_commands.py
arcade/draw_commands.py
arcade/window_commands.py
doc/arcade.rst
doc/examples/index.rst
doc/preprocess_files.py

* Fix a few minor, isolated documentation rendering issues (code block, function arguments)
* Fixed broken path to gameshell.jpg
* Add table of contents to API and Quick API pages
* Get rid of some `make doc` warnings

Minor fixes to documentation rendering (#316)

---

arcade/text.py

Fix error message on text.draw_text:anchor_y

Fix error message on text.draw_text:anchor_y (#1)

---

arcade/__init__.py
arcade/draw_commands.py
arcade/emitter.py
arcade/emitter_simple.py
arcade/examples/frametime_plotter.py
arcade/examples/particle_fireworks.py
arcade/examples/particle_systems.py
arcade/particle.py
arcade/utils.py

As I was watching @pvcraven 's Arcade talk from PyCon 2018, I noticed that [particles where mentioned in the "What's Next" portion of the talk](https://www.youtube.com/watch?v=DAWHMHMPVHU&t=24m2s).  I thought I'd take a stab at an initial implementation of particle systems to get things rolling.  
I focused on providing the user flexibility (the "what will the particle systems be able to do") and very little effort on the underlying implementation details (the "how") at this point (simply using `Sprite` and `SpriteList`).
I have something functional, so, I'd love it if the community could grab this PR, run [`examples/particle_systems.py`](https://github.com/pvcraven/arcade/blob/1874f5554b1ca774d544d7e9565deadc35fbc3ae/arcade/examples/particle_systems.py) and …

Add particle systems and supporting example scripts #333

---

arcade/examples/frametime_plotter.py
arcade/examples/particle_fireworks.py

PyCharm's profiler was reporting that drawing this one line of text was accounting for 7% of the total CPU time taken by particle_fireworks.py.  I knew this way of drawing text is slow, but it was slower than I thought.  And, removing it makes the fireworks demo run more smoothly (45 fps on average to near 60 fps)
Also added FPS calculation to frametime_plotter.py.

Remove slow text drawing from particle_fireworks.py #333

---

arcade/__init__.py
arcade/arcade_types.py
arcade/emitter.py
arcade/emitter_simple.py
arcade/examples/particle_fireworks.py
arcade/examples/particle_stress.py
arcade/examples/particle_systems.py
arcade/particle.py
arcade/utils.py
tests/unit/test_utils.py

- Remove pymunk dependency by replacing pymunk.Vec2d with 2-tuples
- Use Point (and newly added Vector) type hints to represent 2-tuples
- remove matplotlib dependency (via FrametimePlotter).  FrametimePlotter is only used by files in examples/ now.
- rename "pos" and "vel" parameters in Emitter and Particle class hierarchies to "center_xy" and "change_xy" to indicate that they take 2-tuples and to be more consistent with naming elsewhere in the codebase.    
- added vector class (utils._Vec2) to help with internal implementation details.  This class is not meant to be a part of the public interface (ex: function parameters or return values) 
- updated all Emitter test scripts in examples/
- created some (very light coverage) unit tests for the utils.py file, including the new _Vec2 …

Remove dependency on pymunk and matplotlib #343

---

arcade/sprite.py
tests/__init__.py
tests/unit2/test_drawing_primitives.py
tests/unit2/test_sprite.py

Sprite.set_position calls Sprite._set_position with an extra self argument. This argument obviously should not be there ;-)
I fixed a few random bits trying to run all tests locally. This should make it behave better with newer versions of pytest and in Linux. (I did **not** manage to run the full test suite successfully, but it now passes more tests than before)

Fix error in Sprite.set_position

---

arcade/physics_engines.py
tests/unit2/test_physics_engine_platformer.py

This adds arbitrary jump limits to the platforming physics engine. I created a different function to enable it because we don't want to assume the user wants to allow this functionality. Since it requires the user to update the jump counter themselves, if we default to a value of 1 for allowed_jumps, for example, then can_jump will break for users who don't add a call to increment_jump_counter. This would break existing code.
As written, this should allow existing code to continue working as-is, but it will require a user to call increment_jump_counter when they jump if they want to use this functionality.

Add platforming multi-jump support

---

arcade/sprite.py

Sprites can now move forwards based on their angle. This included adding support for radian angles.
Also included are methods to move backwards called reverse and a strafing function for lateral
movement perpendicular to the Sprite's angle. Turn left and right are added for those familiar
with turtle graphics, summing the basic functions normally included.
This should resolve Issue 323.

Add support for Sprite.forward/reverse/turn_left/right/strafe/stop

---

arcade/draw_commands.py
tests/unit2/test_load_textures.py

Fixes issue #282
This is a simple adaptation of load_texture to loading multiple Textures.
Added scale parameter to match other, related functions.
Added simple unit test as a copy of test_animated_sprite.

Add texture caching to load_textures

---

arcade/application.py

set_update_rate was always passed in a hardcoded value of 1/60 in the
Window constructor, ignoring the user-requested value.
Also fixes minor documentation errors
* typo: refuent -> frequent
* typo: 1 / 20 means 60 fps -> 1 / 60 means 60 fps
* missing documentation for antialiasing parameter

#424 Correctly document and set update rate in Window constructor

---

arcade/draw_commands.py

The Pillow method [`.ellipse()`](https://pillow.readthedocs.io/en/3.1.x/reference/ImageDraw.html#PIL.ImageDraw.PIL.ImageDraw.Draw.ellipse) takes points as a bounding box, rather than origin plus radius.
Also, adjusted `make_soft_circle_texture` to draw within bounding box (circles were getting clipped one pixel).

Fix make_circle_texture to draw within bounding box.

---

arcade/sprite.py
tests/unit2/test_sprite_collision.py

done:
- `sprite.collides_with_point(self, point: Point) -> bool`
- `sprite.collides_with_sprite(self, other: 'Sprite') -> bool`
- `sprite.collides_with_list(self, sprite_list: list) -> list`
todo:
- Add `sprite_list.collides_with_point(point: Point) -> bool`
- Add `sprite_list.collides_with_sprite(sprite: Sprite) -> bool`
Wondering:
1. In the Sprite methods, I needed to import functions (e.g., `from arcade.geometry import check_for_collision`) to avoid circular imports that were crashing the program. Is this acceptable?
2. Is it worth making a general `Sprite.collides_with(other: Union(Point, Sprite, SpriteList)) -> Union(bool, SpriteList)` function that, depending on the provided argument, will call the appropriate function to allow for:
```python
if sprite_one.collides_with(point):
pass …
```

[WIP] Add collision methods to Sprite (with tests)

---

.travis.yml
arcade/examples/perf_test/stress_test_draw_moving_pygame.py
arcade/examples/text_loc_example_done.py
doc/examples/install_requires.py
requirements.txt
requirements_dev.txt

__XlibScreen(display=<pyglet.canvas.xlib.XlibDisplay object at 0x7f9778ae6320>, x=0, y=0, width=1024, height=768, xinerama=0)__ is being created in Travis CI but __get_matching_configs()__ is failing to return any configs for the template:
```
template = XlibConfig([('double_buffer', True),
('stereo', None),
('buffer_size', None),
('aux_buffers', None),
('sample_buff...cum_alpha_size', None),
('major_version', 3),
('minor_version', 3),
('forward_compatible', None),
('debug', None)])
```
Are __'major_version', 3 and 'minor_version', 3__ the correct values?

Travis CI: Reenable pytest

---

.travis.yml

Xenial and macOS pass the flake8 and pytest test.
Bionic is run in __allow_failures__ mode for now because of a Pyglet-related [__ImportError: Library "GLU" not found.__](https://travis-ci.com/cclauss/arcade/jobs/222180843#L348)
Run __pytest tests/unit__ but ignore the __unit2__ tests for now because they currently fail on Travis CI.
Results: https://travis-ci.com/cclauss/arcade/builds/121833068

Travis CI:  Run on xenial, bionic, macOS, and Windows 

---

.travis.yml

masOS has builtin OpenGL support so we can run the __tests/unit2__.
__if [ "$TRAVIS_OS_NAME" == "osx" ]; then pytest tests/unit2; fi__

Travis CI: Run all tests on macOS

---

.travis.yml
setup.py

Closes #469
Refs #471
You could also expand the test matrix to test on python 3.6 on a wider variety of platforms, if you wanted.

require dataclasses on python 3.6

---

arcade/sprite.py

#469 
Small change to raise a better error when using python 3.6.
There might be a better way to do it but I thought I would try my hand at a PR since it was easy.

raise better error on dataclasses missing

---

.travis.yml

On macOS, `brew install python` would yield Python 3.8 but it takes a few minutes to install.

Travis CI: Upgrade to Python 3.8 except on macOS

---

arcade/sprite.py
arcade/tilemap.py

Support tilesets from tmx files.
Prior implementation required the use of a "collection of images" when using a TMX.  This patch adds support for tilesets.  Key changes relative to a collection of images that happen when working with a tile set:
* The `image` is defined in the top level tileset,
* Individual `tiles` are only defined if they add custom data (such as a non-standard bounding box), and
* The sprite must be cropped out of the top level image.
This is accomplished by:
* Creating "virtual" tiles when needed for sprites from a tile set,
* Manually setting the top level `image` in the tile for any sprite from a tile set, and
* Explicitly passing cropping data when creating a sprite from a `tile`.
This closes #511.

Tile Set Support for TMX

---

arcade/tilemap.py

Removed check for GID within bounds of tileset count, added check for tile object not being found.
Tested with my project which shows the issue, but needs further buddy testing

Fix for issue #527

---

arcade/examples/particle_fireworks.py
arcade/examples/particle_stress.py
arcade/examples/particle_systems.py

- fix paths to images
- fix particle_systems.py as it was breaking after displaying the first 4 particle systems
- fix "how to run" command in docstrings
- minor tweaks to visuals of particle_fireworks.py

Fix broken particle_systems.py example #558

---

arcade/text.py

Also, include the initial alpha value in the text_sprite.
Resolves #562

Only use RGB (not alpha) for text cache name.

---

arcade/sprite.py

Hey, hopefully doing this correctly.
Firstly, I also tweaked a couple comments to better describe what the functions do.
For the actual rotation_point I used a float list to represent the displacement from the center_x and center_y. Then whenever the angle changes we rotate_point and set_position.
Almost certainly I have not done the get/set stuff right... I think I need  the underscore in front of get and set (_get and _set). I do not have much experience with this and some functions have it some don't???
I did:
`rotate_x, rotate_y = self.rotation_point`
Before we check to see if we need them, I think this only saves process time if it does have a rotation point (which I feel is the less likely case) so it might be better to not do this?

Point a sprite rotates around

---

arcade/sprite.py

For some Sprites the heuristics at the start of the function don't work and get_adjusted_hit_box() would return Nonsense due to a missing line:
Line 315:  x, y = x-self.center_x, y-self.center_y
Without this, it would scale wrong, rotate wrong, and generally return wrong values. 
This has been fixed alongside various cleanup in the surrounding for loop.
Explanation: When a point is not transported to sit on the origin before scaling, it is scaled based on how far from the origin it is, not on how far from its center. Same is true for rotation. The corresponding transportation back existed already, though, so it looks like an oversight, plain and simple. 
This was not discovered earlier because for one, most Sprites have textures, and second, the problem doesn't manifest for the default …

Fix for Issue #602: Sprite.get_adjusted_hit_box()

---

arcade/application.py

Currently method `get_system_mouse_cursor` is returning `None` instead of the cursor instance

Fix missing return in get system mouse cursor

---

arcade/texture.py

- I went through the docstrings in _`texture.py`_ and fixed inconsistent punctuation and modified phrasing where it improved sentence flow. I also added links to object types _(ala :class:`ObjType`)_ to make the HTML documentation easier to navigate.
- I changed a stray method that was using Google docstring style to what the the rest of the project uses. I don't think this was intended?
- I fixed an error with a _`PIL.Image`_ type annotation _(should have been PIL.Image.Image)_ a string to your local project directory being displayed on the documentation page. It now links to the PIL docs appropriately.
- I added the docstring for the _`load_spritesheet`_ method.
If there is anything you disagree with please let me know and I can modify as needed.

Cleaned up docstrings and annotations in 'texture.py'.

---

arcade/text.py

Empty strings results into zero width, which throws an exception.

Fix invalid empty text width

---

arcade/examples/tmx_object_demo.py
arcade/resources/tmx_maps/test_objects.tmx
arcade/tilemap.py
tests/unit2/test_tilemap_objects.py

This allows getting a layer by name as well as traversing layer groups to find a layer.  Ex: 'mylayer' or 'mygroup/mylayer'.  Leading and trailing slashes are stripped out to avoid errors.

Allow getting tmx layer by path

---

arcade/sound.py

Added  `volume` and `pan` args to match the `play()` function of the `Sound` class to recommend use of `play_sound()` instead of `play()`.
See also #645
This is my first pull request, feedback would be appreciated. :)

Added volume and pan arguments in play_sound

---

arcade/gl/texture.py

I am experimenting on the edge artifact issue, and I bumped into a small bug with Texture.read, which resulted in a silent crash because of an allocation error.

fix_texture_read

---

arcade/sprite_list.py

Both versions that I proposed in #660 seems to work and fix the edge artifact issue.
I compared both versions and it seems that the half-pixel solution slightly reduces the quality of the sprites. However, duplicating the border of the sprite texture and using a full pixel offset gives a result close to the previous ones.   
The edge artifact will still happen int tilings if there is some transparent overlap in the texture (like for emulating orthographic perspective). This can only be solved by the author of the texture, by copying the RGB color of the visible edges to the neighboring transparent pixels (which alpha value is kept as 0).

Fix border artifact

---

arcade/experimental/camera.py

Converts the mouse coordinates (or screen space) to the world/camera coordinates. Could work on the name though, maybe it's a bit too long.

Added mouse_to_world_coordinates

---

arcade/application.py

Fixes #701 
An alternative to this dynamic setup could be to introduce a `on_show_view()` which is guaranteed to be called the right amount of times and deprecate the other one.

#701 Fix on_show called twice
